import { Octokit } from '@octokit/rest';
import { GitHubIssueRequest } from '@/types';

export interface GitHubIssueResponse {
  success: boolean;
  issueUrl?: string;
  issueNumber?: number;
  previewBody?: string;
  error?: string;
  isMockPreview?: boolean;
}

export function buildGitHubIssueBody(data: GitHubIssueRequest): string {
  const tagsFormatted = data.tags.map((t) => `\`${t}\``).join(' ');

  return `## 🚨 AutoTriage AI - Automated Bug Triage Report

### 📌 Overview
- **Severity**: \`${data.severity}\`
- **Category**: \`${data.category}\`
- **Tags**: ${tagsFormatted}

---

### 🔍 Root Cause Analysis (RCA)
${data.rootCause}

---

### 🛠️ Suggested Patch / Solution
\`\`\`diff
${data.suggestedFix}
\`\`\`

---

> *Automated issue generated by **AutoTriage AI Maintenance Agent**.*
`;
}

export async function createGitHubIssue(data: GitHubIssueRequest): Promise<GitHubIssueResponse> {
  const issueBody = buildGitHubIssueBody(data);
  const token = data.githubToken || process.env.GITHUB_TOKEN;
  const owner = data.repoOwner || process.env.GITHUB_OWNER;
  const repo = data.repoName || process.env.GITHUB_REPO;

  if (!token || !owner || !repo) {
    return {
      success: true,
      isMockPreview: true,
      issueUrl: `https://github.com/${owner || 'acme-corp'}/${repo || 'main-app'}/issues/new?title=${encodeURIComponent(
        `[${data.severity}] ${data.title}`
      )}&body=${encodeURIComponent(issueBody)}`,
      issueNumber: Math.floor(100 + Math.random() * 900),
      previewBody: issueBody,
    };
  }

  try {
    const octokit = new Octokit({ auth: token });

    const labels = [
      data.severity.toLowerCase(),
      data.category.toLowerCase(),
      ...data.tags,
    ].filter(Boolean);

    const response = await octokit.issues.create({
      owner,
      repo,
      title: `[${data.severity}] ${data.title}`,
      body: issueBody,
      labels,
    });

    return {
      success: true,
      issueUrl: response.data.html_url,
      issueNumber: response.data.number,
      previewBody: issueBody,
      isMockPreview: false,
    };
  } catch (err: any) {
    console.error('GitHub API Error:', err);
    return {
      success: false,
      error: err.message || 'Failed to create GitHub issue',
      previewBody: issueBody,
    };
  }
}
