import { WebhookNotifyRequest } from '@/types';

export interface WebhookResponse {
  success: boolean;
  message: string;
  error?: string;
  isMockPreview?: boolean;
}

export function getSeverityColorHex(severity: string): string {
  switch (severity) {
    case 'P0-Critical':
      return '#ef4444'; // Red
    case 'P1-High':
      return '#f97316'; // Orange
    case 'P2-Medium':
      return '#eab308'; // Yellow / Amber
    case 'P3-Low':
    default:
      return '#3b82f6'; // Blue / Slate
  }
}

export function getSeverityColorInt(severity: string): number {
  switch (severity) {
    case 'P0-Critical':
      return 15684420; // 0xEF4444
    case 'P1-High':
      return 16347926; // 0xF97316
    case 'P2-Medium':
      return 15381256; // 0xEAB308
    case 'P3-Low':
    default:
      return 3900150; // 0x3B82F6
  }
}

export function buildDiscordPayload(data: WebhookNotifyRequest) {
  const { triageResult } = data;
  const color = getSeverityColorInt(triageResult.severity);

  // Truncate long code snippets for Discordembed max length (1024 chars per field)
  const fixSnippet = triageResult.suggestedFix.length > 950 
    ? triageResult.suggestedFix.substring(0, 950) + '\n... [truncated]' 
    : triageResult.suggestedFix;

  const rootCauseSnippet = triageResult.rootCause.length > 950
    ? triageResult.rootCause.substring(0, 950) + '...'
    : triageResult.rootCause;

  return {
    username: 'AutoTriage AI',
    embeds: [
      {
        title: `🚨 [${triageResult.severity}] ${triageResult.title}`,
        color: color,
        fields: [
          {
            name: '📌 Category & Tags',
            value: `**Category:** ${triageResult.category}\n**Tags:** ${triageResult.tags.map((t) => `\`${t}\``).join(', ')}`,
            inline: false,
          },
          {
            name: '🔍 Root Cause Analysis (RCA)',
            value: rootCauseSnippet,
            inline: false,
          },
          {
            name: '🛠️ Suggested Patch / Diff',
            value: `\`\`\`diff\n${fixSnippet}\n\`\`\``,
            inline: false,
          },
        ],
        footer: {
          text: `AutoTriage AI Maintenance Engineer Agent • ${new Date().toLocaleTimeString()}`,
        },
        timestamp: new Date().toISOString(),
      },
    ],
  };
}

export function buildSlackPayload(data: WebhookNotifyRequest) {
  const { triageResult } = data;
  const colorHex = getSeverityColorHex(triageResult.severity);

  const fixSnippet = triageResult.suggestedFix.length > 2000 
    ? triageResult.suggestedFix.substring(0, 2000) + '\n... [truncated]' 
    : triageResult.suggestedFix;

  return {
    text: `🚨 *[${triageResult.severity}] ${triageResult.title}*`,
    attachments: [
      {
        color: colorHex,
        blocks: [
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: `*AutoTriage AI Alert*\n*Category:* ${triageResult.category} | *Tags:* ${triageResult.tags.map((t) => `\`${t}\``).join(' ')}`,
            },
          },
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: `*🔍 Root Cause Analysis (RCA)*\n${triageResult.rootCause}`,
            },
          },
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: `*🛠️ Suggested Fix*\n\`\`\`${fixSnippet}\`\`\``,
            },
          },
          {
            type: 'context',
            elements: [
              {
                type: 'mrkdwn',
                text: `Generated by *AutoTriage AI Agent* at ${new Date().toLocaleString()}`,
              },
            ],
          },
        ],
      },
    ],
  };
}

export async function sendWebhookNotification(data: WebhookNotifyRequest): Promise<WebhookResponse> {
  const { webhookUrl, platform } = data;

  if (!webhookUrl || !webhookUrl.startsWith('http')) {
    return {
      success: true,
      isMockPreview: true,
      message: `[Mock Dispatch] ${platform.toUpperCase()} webhook payload formatted and validated successfully!`,
    };
  }

  try {
    const payload = platform === 'discord' ? buildDiscordPayload(data) : buildSlackPayload(data);

    const res = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`Webhook endpoint returned HTTP ${res.status}: ${errText}`);
    }

    return {
      success: true,
      message: `Webhook alert dispatched successfully to ${platform.toUpperCase()}!`,
    };
  } catch (err: any) {
    console.error('Webhook notification error:', err);
    return {
      success: false,
      message: 'Failed to send webhook notification',
      error: err.message || 'Network error',
    };
  }
}
